/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-04 01:10:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import table.model.vo.Notice;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/82104/Desktop/workplaces/web-server-workplace/guleumingWebProject/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1634515006000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("table.model.vo.Notice");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");

    int rewardTotal = (Integer)request.getAttribute("rewardTotal");
  	int noticeTotal = (Integer)request.getAttribute("noticeTotal");
  	int eventTotal = (Integer)request.getAttribute("eventTotal");
    ArrayList<Notice>list = (ArrayList<Notice>) request.getAttribute("list");
   
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style></style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/KimMinji/index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/defaultCss/default.css\">\r\n");
      out.write("<!-- 폰트 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/defaultCss/font.css\">\r\n");
      out.write("<!-- jQuery라이브러리 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.ulslide.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>구르밍</title>\r\n");
      out.write("<style>\r\n");
      out.write("   .btnWrap{\r\n");
      out.write("	width:400px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	margin-top:30px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.moreBtn {\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	height:50px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight:500;\r\n");
      out.write("	background-color:white;\r\n");
      out.write("	border: 1px solid #eaebed;\r\n");
      out.write("	 border-radius: 5px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	cursor : pointer;\r\n");
      out.write("	margin : 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("		<div class=\"mainBanner\">\r\n");
      out.write("            <ul id=\"bannerImg\">\r\n");
      out.write("			<li class=\"slideImg\"><a href=\"#\"><img src=\"/img/KimMinji/main_01.png\"></a></li>\r\n");
      out.write("			<li class=\"slideImg\"><a href=\"#\"><img src=\"/img/KimMinji/main_02.png\"></a></li>\r\n");
      out.write("			<li class=\"slideImg\"><a href=\"#\"><img src=\"/img/KimMinji/main_03.png\"></a></li>\r\n");
      out.write("			<li class=\"slideImg\"><a href=\"#\"><img src=\"/img/KimMinji/main_04.png\"></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      	<div id=\"goodsWrap\">\r\n");
      out.write("      	<div id=\"goodsTitle\">\r\n");
      out.write("      	<h1><a href=\"/fundingList\">리워드 프로젝트 <img src=\"/img/KimMinji/right.png\" width=\"20px;\"></a></h1>\r\n");
      out.write("      	<p>구르밍의 핫한 프로젝트들을 만나보세요</p>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<select id=\"selected\">\r\n");
      out.write("      	<option value=\"new\" selected>최신순</option>\r\n");
      out.write("      	<option value=\"best\">인기순</option>	\r\n");
      out.write("      	</select>\r\n");
      out.write("      	<div class=\"goodsList\"></div>\r\n");
      out.write("     <div class=\"btnWrap\" ><button class=\"moreBtn\"  currentCount=\"6\" totalCount=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rewardTotal }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"7\" id=\"more\">리워드 프로젝트 더보기</button></div>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<div class=\"main_banner\">\r\n");
      out.write("	      	<a href=\"/fundingList\">      	\r\n");
      out.write("	      		<img src=\"/img/KimMinji/main_b01.png\">\r\n");
      out.write("	      	</a>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<div id=\"noticeWrap\">\r\n");
      out.write("      	<div id=\"noticeTitle\">\r\n");
      out.write("      	<h1><a href=\"/noticeList\">공지사항<img src=\"/img/KimMinji/right.png\" width=\"20px;\"></a></h1>\r\n");
      out.write("      	<p>구르밍의 새로운 소식을 전달해드립니다</p>\r\n");
      out.write("      	<div class=\"noticeList\">	</div>\r\n");
      out.write("      	</div>\r\n");
      out.write("     <div class=\"btnWrap\" ><button class=\"moreBtn\" currentCount=\"4\" totalCount=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticeTotal }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"5\" id=\"moreNotice\">새소식 더보기</button></div>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<div class=\"main_banner\">\r\n");
      out.write("	      	<a href=\"/funder/funderList?reqPage=1&funderCategory=전체\">      	\r\n");
      out.write("	      		<img src=\"/img/KimMinji/main_b02.png\">\r\n");
      out.write("	      	</a>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	<div id=\"eventWrap\">\r\n");
      out.write("      	<div id=\"eventTitle\">\r\n");
      out.write("      	<h1><a href=\"/eventList\">이벤트<img src=\"/img/KimMinji/right.png\" width=\"20px;\"></a></h1>\r\n");
      out.write("      	<p>구르밍의 이벤트 소식입니다</p>\r\n");
      out.write("      	<div class=\"eventList\">	</div>\r\n");
      out.write("      	</div>\r\n");
      out.write("      	\r\n");
      out.write("     <div class=\"btnWrap\" ><button class=\"moreBtn\" currentCount=\"2\" totalCount=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventTotal }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"3\" id=\"moreEvent\">이벤트 더보기</button></div>\r\n");
      out.write("      	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("		<script>\r\n");
      out.write("		setInterval(function(){ \r\n");
      out.write("		    $(' #bannerImg>li').delay(1500);\r\n");
      out.write("		 $(' #bannerImg>li').animate({marginLeft: \"-1200px\"});\r\n");
      out.write("		 $(' #bannerImg>li').delay(1500); \r\n");
      out.write("		 $(' #bannerImg>li').animate({marginLeft: \"-2400px\"});\r\n");
      out.write("		  $(' #bannerImg>li').delay(3000); \r\n");
      out.write("		  $(' #bannerImg>li').animate({marginLeft: \"0px\"}) \r\n");
      out.write("		});\r\n");
      out.write("		  window.onload=function(){\r\n");
      out.write("			  var selected = \"new\";\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url:\"/indexProduct\",\r\n");
      out.write("					data : {selected : selected},\r\n");
      out.write("					type :\"post\",\r\n");
      out.write("					dataType :\"json\",\r\n");
      out.write("					success : function(data) {\r\n");
      out.write("						$(\".goodsList\").empty();\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var f = data[i];\r\n");
      out.write("							var html =\"\";\r\n");
      out.write("							html += \" <div class='goods'>\";\r\n");
      out.write("							html += \" <a href='/fundingView?projectNo=\"+f.projectNo+\"&cMemberNo=0'><img src='/upload/project/\"+f.filepath+\"'></a>\";\r\n");
      out.write("							html += \" <p class='projectTitle'>\"+f.projectTitle+\"</p>\";\r\n");
      out.write("							html += \" <p ><span class='text'>\"+f.totalPrice+\"원펀딩중</span><span class='right'>D-\"+f.period+\"남음</span><spna class='right'>\"+f.percent+\"%진행</span></p></div> \";\r\n");
      out.write("								$(\".goodsList\").append(html);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url :\"/indexNotice\",\r\n");
      out.write("					type:\"post\",\r\n");
      out.write("					dataType :\"json\",\r\n");
      out.write("					success : function(data) {\r\n");
      out.write("						$(\".noticeList\").empty();\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var n = data[i];\r\n");
      out.write("							var html =\"\";\r\n");
      out.write("							html += \" <div class='notice'>\";\r\n");
      out.write("							html += \" <a href='/noticeView?noticeNo=\"+n.noticeNo+ \"'>\"+n.noticeTitle+\"</a></div>\";	\r\n");
      out.write("								$(\".noticeList\").append(html);\r\n");
      out.write("						}\r\n");
      out.write("					}						\r\n");
      out.write("				});\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url :\"/indexEvent\",\r\n");
      out.write("					type:\"post\",\r\n");
      out.write("					dataType :\"json\",\r\n");
      out.write("					success : function(data) {\r\n");
      out.write("						$(\".eventList\").empty();\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var e = data[i];\r\n");
      out.write("							var html =\"\";\r\n");
      out.write("							html += \" <div class='event'>\";\r\n");
      out.write("							html += \"<a href='/eventView?eventNo=\"+e.eventNo + \"'><img src='/upload/event/\"+e.filepath+\"'>\"+e.eventTitle+\"</a></div>\";	\r\n");
      out.write("								$(\".eventList\").append(html);\r\n");
      out.write("			\r\n");
      out.write("		  }\r\n");
      out.write("				}\r\n");
      out.write("				});\r\n");
      out.write("		  }\r\n");
      out.write("			$(\"#selected\").change(function() {\r\n");
      out.write("				var selected = $(this).val();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url:\"/indexProduct\",\r\n");
      out.write("					data : {selected : selected},\r\n");
      out.write("					type :\"post\",\r\n");
      out.write("					dataType :\"json\",\r\n");
      out.write("					success : function(data) {\r\n");
      out.write("						$(\".goodsList\").empty();\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var f = data[i];\r\n");
      out.write("							var html =\"\";\r\n");
      out.write("							html += \" <div class='goods'>\";\r\n");
      out.write("							html += \" <a href='/fundingView?projectNo=\"+f.projectNo+\"&cMemberNo=0'><img src='/upload/project/\"+f.filepath+\"'></a>\";\r\n");
      out.write("							html += \" <p class='projectTitle'>\"+f.projectTitle+\"</p>\";\r\n");
      out.write("							html += \" <p><span class='text'>\"+f.totalPrice+\"원펀딩중</span><span class='right'>D-\"+f.period+\"남음</span><spna class='right'>\"+f.percent+\"%진행</span></p></div> \";\r\n");
      out.write("								$(\".goodsList\").append(html);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#more\").click(function(){//id -> more-btn 눌렀을때 실행할 함수\r\n");
      out.write("				var start = $(this).val();\r\n");
      out.write("				var seleted = $(\"#selected\").val();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/moreProduct\",\r\n");
      out.write("					data : {start:start,\r\n");
      out.write("						selected:seleted},\r\n");
      out.write("					type : \"post\",\r\n");
      out.write("					success : function(data){\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var f = data[i];\r\n");
      out.write("							var html=\"\";\r\n");
      out.write("							html += \" <div class='goods'>\";\r\n");
      out.write("							html += \" <a href='/fundingView?projectNo=\"+f.projectNo+\"&cMemberNo=0'><img src='/upload/project/\"+f.filepath+\"'></a>\";\r\n");
      out.write("							html += \" <p class='projectTitle'>\"+f.projectTitle+\"</p>\";\r\n");
      out.write("							html += \" <p><span class='text'>\"+f.totalPrice+\"원펀딩중</span><span class='right'>D-\"+f.period+\"남음</span><spna class='right'>\"+f.percent+\"%진행</span></p></div> \";\r\n");
      out.write("								$(\".goodsList\").append(html);\r\n");
      out.write("						}\r\n");
      out.write("						$(\"#more\").val(Number(start)+3);\r\n");
      out.write("						var curr = Number($(\"#more\").attr(\"currentCount\"));\r\n");
      out.write("						$(\"#more\").attr(\"currentCount\", curr + data.length);\r\n");
      out.write("						var totalCount = $(\"#more\").attr(\"totalCount\");\r\n");
      out.write("						var currCount = $(\"#more\").attr(\"currentCount\");\r\n");
      out.write("						if(currCount == totalCount){\r\n");
      out.write("							$(\"#more\").css(\"display\", \"none\");\r\n");
      out.write("							$(\"#more\").prop(\"disabled\",false);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#moreNotice\").click(function(){//id -> more-btn 눌렀을때 실행할 함수\r\n");
      out.write("				var start = $(this).val();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/moreNotice\",\r\n");
      out.write("					data : {start:start},\r\n");
      out.write("					type : \"post\",\r\n");
      out.write("					success : function(data){\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var n = data[i];\r\n");
      out.write("							var html=\"\";\r\n");
      out.write("							html += \" <div class='notice'>\";\r\n");
      out.write("							html += \" <a href='/noticeView?noticeNo=\"+n.noticeNo+ \"'>\"+n.noticeTitle+\"</a></div>\";	\r\n");
      out.write("								$(\".noticeList\").append(html);\r\n");
      out.write("						}\r\n");
      out.write("						$(\"#moreNotice\").val(Number(start)+1);\r\n");
      out.write("						var curr = Number($(\"#moreNotice\").attr(\"currentCount\"));\r\n");
      out.write("						$(\"#moreNotice\").attr(\"currentCount\", curr + data.length);\r\n");
      out.write("						var totalCount = $(\"#moreNotice\").attr(\"totalCount\");\r\n");
      out.write("						var currCount = $(\"#moreNotice\").attr(\"currentCount\");\r\n");
      out.write("						if(currCount == totalCount){\r\n");
      out.write("							$(\"#moreNotice\").css(\"display\", \"none\");\r\n");
      out.write("							$(\"#moreNotice\").prop(\"disabled\",false);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			$(\"#moreEvent\").click(function(){//id -> more-btn 눌렀을때 실행할 함수\r\n");
      out.write("				var start = $(this).val();\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/moreEvent\",\r\n");
      out.write("					data : {start:start},\r\n");
      out.write("					type : \"post\",\r\n");
      out.write("					success : function(data){\r\n");
      out.write("						for(var i=0;i<data.length;i++){\r\n");
      out.write("							var e = data[i];\r\n");
      out.write("							var html =\"\";\r\n");
      out.write("							html += \" <div class='event'>\";\r\n");
      out.write("							html += \"<a href='/eventView?eventNo=\"+e.eventNo + \"'><img src='/upload/event/\"+e.filepath+\"'>\"+e.eventTitle+\"</a></div>\";	\r\n");
      out.write("								$(\".eventList\").append(html);\r\n");
      out.write("			\r\n");
      out.write("						}\r\n");
      out.write("						$(\"#moreEvent\").val(Number(start)+2);\r\n");
      out.write("						var curr = Number($(\"#moreEvent\").attr(\"currentCount\"));\r\n");
      out.write("						$(\"#moreEvent\").attr(\"currentCount\", curr + data.length);\r\n");
      out.write("						var totalCount = $(\"#moreEvent\").attr(\"totalCount\");\r\n");
      out.write("						var currCount = $(\"#moreEvent\").attr(\"currentCount\");\r\n");
      out.write("						if(currCount == totalCount){\r\n");
      out.write("							$(\"#moreEvent\").css(\"display\", \"none\");\r\n");
      out.write("							$(\"#moreEvent\").prop(\"disabled\",false);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			</script>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /index.jsp(50,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /index.jsp(267,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/views/common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
